### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by dinkar--s** [xinjli/allosaurus#10]
Hi, 

Looks like a great program.

However, I was having trouble building allosaurus. I am on Ubuntu 16.04 and when I do 'pip install allosaurus' I get

  Building wheel for llvmlite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-r4C97N/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-r4C97N/llvmlite/s
etup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_whee
l -d /tmp/pip-wheel-AzDXdO
       cwd: /tmp/pip-install-r4C97N/llvmlite/
  Complete output (7 lines):
  running bdist_wheel
  /usr/bin/python /tmp/pip-install-r4C97N/llvmlite/ffi/build.py
    File "/tmp/pip-install-r4C97N/llvmlite/ffi/build.py", line 122
      raise ValueError(msg.format(_ver_check_skip)) from e
                                                       ^
  SyntaxError: invalid syntax
  error: command '/usr/bin/python' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite

On the web, there were suggestions to use 'python -m pip ...' and also try install llvm. I did both, but it didn't help

Appreciate any help

**Comment by xinjli** [comment]
I guess it might be the python version issue. We are using python>=3.6 and it has not install problems so far.

There is a related issue here might be helpful for you.
https://github.com/numba/numba/issues/5855

**Comment by dinkar--s** [comment]
I managed to install allosaurus by using a specific version of llvmlite using _pip install llvmlite==0.31.0_ It seems to have something to do with LLVM_CONFIG not being set properly. The reason for this is given in _https://stackoverflow.com/questions/61475274/runtimeerror-path-failed-executing-please-point-llvm-config-to-the-path-for_ Thanks very much for the help
