### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by unilight** [xinjli/allosaurus#16]
Hi, I tried to install with `pip install allosaurus` and tried to run `python -m allosaurus.run -i <path>/cmu_us_slt_arctic/wav/arctic_b0340.wav` where I try to transcribe a 16kHz wave file from the CMU ARCTIC dataset. I got the following results:
```
$ python -m allosaurus.run -i <path>/cmu_us_slt_arctic/wav/arctic_b0340.wav
ð i z k w ɪ k l ɪ tʰ ə l dʒ o j z ʌ v h ɹ̩ z w ɹ̩ s ɔ ɹ s ə z ʌ v dʒ o j t ə h ɪ m
Segmentation fault (コアダンプ)
```
The last Japanese word means "core dump". Has anyone encountered this issue before?
FYI, I am using python 3.7.7 and my torch version is `1.5.1+cu101`.

**Comment by xinjli** [comment]
Hi,

Thanks for reporting the error, 
Unfortunately, I did not see this type of error before.

Do you always get this error or you see this occasionally?
Does the default sample.wav give you the same error?

**Comment by unilight** [comment]
> Does the default sample.wav give you the same error?

No, it worked normally with sample.wav.

> Do you always get this error or you see this occasionally?

It's hard for me to answer this one because I was just trying to test on some other wav files. 

I can provide some other info about the difference between the two files.

```
$ soxi sample.wav

Input File     : 'sample.wav'
Channels       : 1
Sample Rate    : 8000
Precision      : 16-bit
Duration       : 00:00:01.07 = 8526 samples ~ 79.9312 CDDA sectors
File Size      : 17.1k
Bit Rate       : 128k
Sample Encoding: 16-bit Signed Integer PCM

$ soxi <path>/cmu_us_slt_arctic/wav/arctic_b0340.wav

Input File     : '<path>/cmu_us_slt_arctic/wav/arctic_b0340.wav'
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Duration       : 00:00:03.83 = 61360 samples ~ 287.625 CDDA sectors
File Size      : 123k
Bit Rate       : 256k
Sample Encoding: 16-bit Signed Integer PCM
```

I am also getting core dump if I input a directory.

```
$ python -m allosaurus.run -i <path>/cmu_us_slt_arctic/wav/
...
arctic_b0532.wav ð æ tʰ l ɔ ŋ f ɛ l o w t͡ʃʲ æ p m o w s t l a j k l i h æ d ɹ ɪ tʰ ə n k a w n tʰ l ə s b̥ ʊ k s ʌ v p o w ə t ɹ i
arctic_b0533.wav h ɪ z æ b n ɔ ɹ m ə l p a w ɹ̩ v ɪ ʒ ə n m e j d æ b s t ɹ æ k ʃ ə n z t e j k ɑ n k ɑ n k ɹ i tʰ f ɔ ɹ m
arctic_b0534.wav a j l t ɛ l j u ð ə l e j b̥ ɹ ɛ ɹ i æ n d s ɛ d w ɪ ð ə b̥ ɹ a j tʰ ə n ɪ ŋ f e j s
arctic_b0535.wav h i ɹ ɛ d h ɪ z f ɹ æ g m ə n t s ə l a w d
arctic_b0536.wav p ʁ e j f ɔ j d ɪ d a j t ɛ l j u
arctic_b0537.wav b̥ ʌ tʰ ʃ i h æ d b̥ ɪ k ʌ m æ n ɒ w ɹ̩ t ɒ m ə n t ɒ n
arctic_b0538.wav æ tʰ ð ə b̥ ɛ s t ð e j w ɹ̩ n ɛ s ə s ɛ ɹ i ɛ k s ɛ s ɹ̩ i z
arctic_b0539.wav j u w ɹ̩ m e j k ɪ ŋ ð ɛ m t ɔ k x ɑ p ɹ u θ tʃ ɑ ɹ dʒ d h ɪ m
Segmentation fault (コアダンプ)
```

**Comment by xinjli** [comment]
hmm, I tried the arctic file you failed but did not see any problems.
your python version and torch version looks good, maybe your machine's memory is not large enough?

Do you have any stack tracking details?
I think you can catch it with gdb or some other tools.
