### ISSUE TITLE
Deterministic output

### ISSUE THREAD

**Issue by eremingt** [xinjli/allosaurus#21]
I noticed that there is some variability in the output from call to call. For example, I just ran the same 15 second sample 10 times and the output contained varying numbers of phones:

`[197, 198, 200, 199, 196, 195, 203, 195, 198, 197]`

Is it possible to configure/modify the code slightly to generate deterministic results? I'm not sure, but I suspect this has something to do with Torch.

**Comment by xinjli** [comment]
Hi,

The random effects are actually coming from a preprocessing step called dithering, which is related to quantization errors.
It is not that important in the inference stage, so I just updated in the latest version to disable this preprocess.

If you upgrade to the latest version, the results should be deterministic now.

**Comment by eremingt** [comment]
Awesome, closing! New results from same file:

[190, 190, 190, 190, 190, 190, 190, 190, 190, 190]

Consistent and slightly lower number of identified phones than before.
