### ISSUE TITLE
Can't download models

### ISSUE THREAD

**Issue by JazminVidal** [xinjli/allosaurus#29]
Hi!

I am trying to download the English model by running: 

```
python -m allosaurus.bin.download_model -m eng2102
``` 

and I get the following error: 

```
downloading model  eng2102
from:  https://www.pyspeech.com/static/model/recognition/allosaurus/eng2102.tar.gz
to:    /home/j/miniconda3/lib/python3.8/site-packages/allosaurus/pretrained
please wait...
Error: could not download the model
```

Same goes for the other model. 
Is there a way to get them? 

Thanks,

**Comment by xinjli** [comment]
Hi, 

It looks you are using an old version.
The latest one is using a different download URL.
Can you try upgrading or pulling the latest version to try again?

Thanks

**Comment by JazminVidal** [comment]
It worked! Sorry for the inconvenience.
