### ISSUE TITLE
Phone distance metric

### ISSUE THREAD

**Issue by mattare2** [xinjli/allosaurus#32]
Thanks for all your work on allosaurus. It's a really great resource!

For comparing the similarity of two phonetic sequences right now I've been using simple jaccard distance, but it would be nice to use a distance metric that would be sensitive to the fact that phonemes are not equally similar.  Can you recommend a resource that would allow for this kind of distance metric?

Thank you!

**Comment by dmort27** [comment]
Hi @mattare2 , you might consider using the `Distance` module in the PanPhon library (https://github.com/dmort27/panphon). It supports a couple of flavors of feature distance (under which phonologically similar phones are less distant that phonologically dissimilar phones). A phonetic distance metric would probably be better for your purposes, but I phonological distance metric may be adequate. Note that a few of the phones output by allosaurus are not supported by PanPhon. You can generally get reasonable results by removing the diacritics from these segments.

**Comment by xinjli** [comment]
Hi mattare2,

As David just mentioned, the PanPhon library is very useful in your case. I also used it for my other projects and it works pretty well.

Thanks!

**Comment by mattare2** [comment]
Thanks so much!!
