### ISSUE TITLE
Option to extract last layer embeddings of the lstm.

### ISSUE THREAD

**Issue by raotnameh** [xinjli/allosaurus#35]
Hi, 

It would be better if an argument can be passed to extract the embeddings instead of the phones.  @xinjli

**Comment by xinjli** [comment]
Hi, thanks for your suggestion!  I will implement this.

**Comment by raotnameh** [comment]
Hi, I have created a pull request let me know if that works.

**Comment by xinjli** [comment]
Hi thanks for the pull request, I just merged it
