### ISSUE TITLE
Is the output phone or phonemes? 

### ISSUE THREAD

**Issue by raotnameh** [xinjli/allosaurus#55]
@xinjli Just curious is the output a list of phones or phonemes? 
Two cases: 
1. lang_id token provided
2.  lang_id token NOT provided

**Comment by raotnameh** [comment]
@xinjli There are 44 phonemes in English given the IPA [list](https://www.dyslexia-reading-well.com/44-phonemes-in-english.html#:~:text=Despite%20there%20being%20just%2026,used%20to%20represent%20the%20sounds.). 

When I run the command to get a list of phones. they are 67. 
``` python -m allosaurus.bin.list_phone --lang eng  ```

How can I map the phones to phonemes? In the paper, you mention an allophone layer. How do I get the phoneme as an output?

**Comment by xinjli** [comment]
Hi

Sorry for the late reply.
The model currently only supports the output at the phone layer, the phoneme output is not supported yet.
However, you can always map the phone output to phoneme easily by looking up a phone/phoneme (allophone) dictionary.
For example, you can use the allovera mapping https://github.com/dmort27/allovera or  phoible mapping https://phoible.org/inventories/view/160
