### ISSUE TITLE
Prior.txt file path

### ISSUE THREAD

**Issue by Celine-Guan** [xinjli/allosaurus#57]
Hi, thank you for the nice work! I would like to know where should I put the prior.txt file for Prior Customization ? Thanks !

**Comment by xinjli** [comment]
Hi

Thanks for your question!
There is a configuration --prior you can specify to indicate where is your prior file path. It can be anywhere I think.

**Comment by Celine-Guan** [comment]
Thanks for the reply. I added a path of prior.txt in lm/mask.py. It worked :)
