### ISSUE TITLE
Difference in outputs of splitted v/s unsplitted audio file

### ISSUE THREAD

**Issue by 007prateekd** [xinjli/allosaurus#69]
Loved the work. Just a small question.   
I have an audio file of a speech. After applying allosaurus, I am getting satisfactory results. But when I split the audio file based on the words spoken (using timestamps generated by another model) and then apply allosaurus, I get unsatisfactory results. I have checked the individual splitted audio files and they seem to be spliited just fine. For example, the original output for the word _pronouncing_ was `p ɹ o n æ s j ŋ` and the output after applying the model on [this](https://drive.google.com/file/d/1H6-X6ThyhKSMR86l75-ZhliGtAc6Z1y4/view?usp=sharing) splitted audio file was `k o n ɑ n s j ŋ`.     
Do you have any idea why this is happening and how to rectify it?

**Comment by repushko** [comment]
@007prateekd Hi Prateek!
Did you solve the issue on your own? I'm experiencing the same problem and I haven't had a chance to look deeper into this. What is the root cause of such behavior? Have you found it?

**Comment by 007prateekd** [comment]
@repushko Hi there,
If you plot the audio signal of the speech segment you have cut, you will notice the signal starts and ends abruptly instead of starting / ending smoothly from / to 0. I speculate this is the reason why the start and end phones are all messed up while the middle ones seem just fine.
I did try to smoothen the signal out (by windowing) and it did improve the results a bit but it was still unsatisfactory. After consulting, it turns out cutting speech signals is not a great idea and also results in loss of information.
