### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by ThomasBallatore** [xinjli/allosaurus#75]
This is an error and proposed solution on the v2 branch.

After installing v2, I was getting the following cascading errors:

**KeyError: PosixPath('/Users/me/allosaurus/am/module/arch')**
**AttributeError: 'PosixPath' object has no attribute 'startswith'**

I checked out the `__init__.py` file inside of the `arch` directory and it appears that the `iter_modules` function expects the path to be a string, but in this case, a PosixPath object is being passed in instead. 

I fixed the issue locally by calling `str()` on line 8 as follows:

`for (_, module_name, _) in pkgutil.iter_modules([str(package_dir)]):`

I’ve never seen this error before and it might very well have to do with my setup. Fwiw, I’m running Python 3.10.8 on an M2 Mac. 

(And btw, thanks so much for getting v2 up—I'm really excited to play around with it! 🎉)

**Comment by xinjli** [comment]
Hi Thomas

Thanks for trying it!
I did not see this error too, but it might be better to use str instead to prevent this error.
I updated this in the latest commit.
btw the v2 model here did not include Japanese, so it might not work very well for now for Japanese.
But as I mentioned in our email, I am planning to do the language-specific model

Thanks!
